name: Build Docker image
on:
  push:
permissions:
  packages: write
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository witiko/markdown
        uses: actions/checkout@v4
        with:
          repository: witiko/markdown
          ref: main
          fetch-depth: 0
      - name: Build intermediate image witiko/markdown:latest-minimal
        run: DOCKER_BUILDKIT=1 docker build --build-arg TEXLIVE_TAG=latest-minimal --build-arg DEV_IMAGE=true -t witiko/markdown:latest-minimal .
      - name: Checkout Git repository istqborg/istqb_product_base
        uses: actions/checkout@v4
      - name: Build final image ghcr.io/istqborg/istqb_product_base:latest
        run: DOCKER_BUILDKIT=1 docker build -t ghcr.io/istqborg/istqb_product_base:latest .
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image ghcr.io/istqborg/istqb_product_base:latest
        run: docker push ghcr.io/istqborg/istqb_product_base:latest
