name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document to generate references and main.aux
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -shell-escape
      - name: Generate BibTex document for references
        uses: dante-ev/latex-action@latest
        with:
            root_file: main.aux
            compiler: bibtex
            args:
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
            root_file: main.tex
            compiler: pdflatex
            args: -shell-escape
      - name: Compile LaTeX document v2
        uses: dante-ev/latex-action@latest
        with:
            root_file: main.tex
            compiler: pdflatex
            args: -shell-escape
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: main.pdf
