name: Build LaTeX documents
on: [push]
permissions: {contents: write}
jobs:
  validate:
    name: Validate YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Validate example-md/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: example-md/metadata.yml
      - name: Validate syllabus-md/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: syllabus-md/metadata.yml
      - name: Validate bok-md/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: bok-md/metadata.yml
      - name: Validate sample-exam-md/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: sample-exam-md/metadata.yml
      - name: Validate sample-exam-md/questions.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/questions.yml
          target: sample-exam-md/questions.yml
  produce-pdf:
    name: Produce PDF
    needs:
      - validate
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:3.2.0-0-g034c66fb-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install required packages
        run: |
          set -ex
          apt -qy update
          apt -qy install --no-install-recommends dos2unix
      - name: Ensure correct encoding of input files
        run: find -type f \( -iregex '.*\.md$' -o -name '.*\.yml$' \) -exec dos2unix {} +
      - name: Convert EPS images to PDF
        run: find -type f -iregex '.*\.eps$' | parallel epstopdf {} {.}-eps-converted-to.pdf
      - name: Compile LaTeX document example.tex to PDF
        run: latexmk example.tex
      - name: Compile LaTeX document atlas-syllabus.tex to PDF
        run: latexmk atlas-syllabus.tex
      - name: Compile LaTeX document atlas-bok.tex to PDF
        run: latexmk atlas-bok.tex
      - name: Compile LaTeX document sample-exam-questions.tex to PDF
        run: latexmk sample-exam-questions.tex
      - name: Compile LaTeX document sample-exam-answers.tex to PDF
        run: latexmk sample-exam-answers.tex
      - name: Upload PDF documents
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: '*.pdf'
  produce-html:
    name: Produce HTML
    needs:
      - validate
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:3.2.0-0-g034c66fb-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install required packages
        run: |
          set -ex
          apt -qy update
          apt -qy install --no-install-recommends dos2unix tidy
      - name: Ensure correct encoding of input files
        run: find -type f \( -iregex '.*\.md$' -o -name '.*\.yml$' \) -exec dos2unix {} +
      - name: Create output directory html/
        run: mkdir html
      - name: Compile LaTeX document example.tex to HTML
        run: make4ht -s -c istqb.cfg -e istqb.mk4 -d html/example example.tex
      - name: Compile LaTeX document atlas-syllabus.tex to HTML
        run: make4ht -s -c istqb.cfg -e istqb.mk4 -d html/atlas-syllabus atlas-syllabus.tex
      - name: Compile LaTeX document atlas-bok.tex to HTML
        run: make4ht -s -c istqb.cfg -e istqb.mk4 -d html/atlas-bok atlas-bok.tex
      - name: Compile LaTeX document sample-exam-questions.tex to HTML
        run: make4ht -s -c istqb.cfg -e istqb.mk4 -d html/sample-exam-questions sample-exam-questions.tex
      - name: Compile LaTeX document sample-exam-answers.tex to HTML
        run: make4ht -s -c istqb.cfg -e istqb.mk4 -d html/sample-exam-answers sample-exam-answers.tex
      - name: Upload HTML documents
        uses: actions/upload-artifact@v3
        with:
          name: HTML
          path: html/
  produce-ebooks:
    name: Produce EPUB
    needs:
      - validate
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:3.2.0-0-g034c66fb-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install required packages
        run: |
          set -ex
          apt -qy update
          apt -qy install --no-install-recommends dos2unix tidy
      - name: Ensure correct encoding of input files
        run: find -type f \( -iregex '.*\.md$' -o -name '.*\.yml$' \) -exec dos2unix {} +
      - name: Create output directory epub/
        run: mkdir epub
      - name: Compile LaTeX document example.tex to EPUB
        run: tex4ebook -s -c istqb.cfg -e istqb.mk4 -d epub example.tex
      - name: Compile LaTeX document atlas-syllabus.tex to EPUB
        run: tex4ebook -s -c istqb.cfg -e istqb.mk4 -d epub atlas-syllabus.tex
      - name: Compile LaTeX document atlas-bok.tex to EPUB
        run: tex4ebook -s -c istqb.cfg -e istqb.mk4 -d epub atlas-bok.tex
      - name: Compile LaTeX document sample-exam-questions.tex to EPUB
        run: tex4ebook -s -c istqb.cfg -e istqb.mk4 -d epub sample-exam-questions.tex
      - name: Compile LaTeX document sample-exam-answers.tex to EPUB
        run: tex4ebook -s -c istqb.cfg -e istqb.mk4 -d epub sample-exam-answers.tex
      - name: Upload EPUB documents
        uses: actions/upload-artifact@v3
        with:
          name: EPUB
          path: epub
