name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:2.22.0-0-g5a3d0fe-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document example.tex
        run: latexmk -shell-escape -pdf example.tex
      - name: Compile LaTeX document atlas.tex
        run: latexmk -shell-escape -pdf atlas.tex
      - name: Upload PDF documents
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            example.pdf
            atlas.pdf
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            example.pdf
            atlas.pdf
