name: Build LaTeX document
on: [push]
permissions: {contents: write}
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:3.1.0-50-g284f2387-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Ensure correct encoding of input files
        run: |
          set -ex
          apt -qy update
          apt -qy install --no-install-recommends dos2unix
          find -type f \( -name '*.md' -o -name '*.yml' \) -exec dos2unix {} +
      - name: Compile LaTeX document example.tex
        run: latexmk -shell-escape -pdf example.tex
      - name: Compile LaTeX document atlas-syllabus.tex
        run: latexmk -shell-escape -pdf atlas-syllabus.tex
      - name: Compile LaTeX document atlas-bok.tex
        run: latexmk -shell-escape -pdf atlas-bok.tex
      - name: Compile LaTeX document sample-exam-questions.tex
        run: latexmk -shell-escape -pdf sample-exam-questions.tex
      - name: Upload PDF documents
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            example.pdf
            atlas-bok.pdf
            atlas-syllabus.pdf
            sample-exam-questions.pdf
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            example.pdf
            atlas-bok.pdf
            atlas-syllabus.pdf
            sample-exam-questions.pdf
