name: Build LaTeX documents
on: [push]
permissions: {contents: write}
jobs:
  validate:
    name: Validate YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Validate example-document/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: example-document/metadata.yml
      - name: Validate syllabus/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: syllabus/metadata.yml
      - name: Validate body-of-knowledge/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: body-of-knowledge/metadata.yml
      - name: Validate release-notes/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: release-notes/metadata.yml
      - name: Validate accreditation-guidelines/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: accreditation-guidelines/metadata.yml
      - name: Validate sample-exam/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: sample-exam/metadata.yml
      - name: Validate sample-exam/questions.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/questions.yml
          target: sample-exam/questions.yml
  build:
    name: Build LaTeX documents
    needs:
      - validate
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:3.2.0-43-gc109d22b-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Ensure correct encoding of input files
        run: |
          set -ex
          apt -qy update
          apt -qy install --no-install-recommends dos2unix
          find -type f \( -iregex '.*\.md$' -o -name '.*\.yml$' \) -exec dos2unix {} +
      - name: Convert EPS images to PDF
        run: find -type f -iregex '.*\.eps$' | parallel epstopdf {} {.}-eps-converted-to.pdf
      - name: Compile LaTeX document example-document.tex
        run: latexmk -shell-escape -pdf -Werror example-document.tex
      - name: Compile LaTeX document atlas-syllabus.tex
        run: latexmk -shell-escape -pdf -Werror atlas-syllabus.tex
      - name: Compile LaTeX document atlas-body-of-knowledge.tex
        run: latexmk -shell-escape -pdf -Werror atlas-body-of-knowledge.tex
      - name: Compile LaTeX document atlas-release-notes.tex
        run: latexmk -shell-escape -pdf -Werror atlas-release-notes.tex
      - name: Compile LaTeX document atlas-accreditation-guidelines.tex
        run: latexmk -shell-escape -pdf -Werror atlas-accreditation-guidelines.tex
      - name: Compile LaTeX document atlas-sample-exam-questions.tex
        run: latexmk -shell-escape -pdf -Werror atlas-sample-exam-questions.tex
      - name: Compile LaTeX document atlas-sample-exam-answers.tex
        run: latexmk -shell-escape -pdf -Werror atlas-sample-exam-answers.tex
      - name: Upload PDF documents
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            example-document.tex.pdf
            atlas-syllabus.pdf
            atlas-body-of-knowledge.pdf
            atlas-release-notes.pdf
            atlas-accreditation-guidelines.pdf
            atlas-sample-exam-questions.pdf
            atlas-sample-exam-answers.pdf
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            example-document.tex.pdf
            atlas-syllabus.pdf
            atlas-body-of-knowledge.pdf
            atlas-release-notes.pdf
            atlas-accreditation-guidelines.pdf
            atlas-sample-exam-questions.pdf
            atlas-sample-exam-answers.pdf
