name: Build LaTeX documents
on: [push]
permissions: {contents: write}
jobs:
  validate:
    name: Validate YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Validate example-md/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: example-md/metadata.yml
      - name: Validate syllabus-md/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: syllabus-md/metadata.yml
      - name: Validate bok-md/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: bok-md/metadata.yml
      - name: Validate sample-exam-md/metadata.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/metadata.yml
          target: sample-exam-md/metadata.yml
      - name: Validate sample-exam-md/questions.yml
        uses: nrkno/yaml-schema-validator-github-action@v4
        with:
          schema: schema/questions.yml
          target: sample-exam-md/questions.yml
  build:
    name: Build LaTeX documents
    needs:
      - validate
    runs-on: ubuntu-latest
    container:
      image: witiko/markdown:3.2.0-0-g034c66fb-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Ensure correct encoding of input files
        run: |
          set -ex
          apt -qy update
          apt -qy install --no-install-recommends dos2unix
          find -type f \( -iregex '.*\.md$' -o -name '.*\.yml$' \) -exec dos2unix {} +
      - name: Convert EPS images to PDF
        run: find -type f -iregex '.*\.eps$' | parallel epstopdf {} {.}-eps-converted-to.pdf
      - name: Compile LaTeX document example.tex
        run: latexmk -shell-escape -pdf -Werror example.tex
      - name: Compile LaTeX document atlas-syllabus.tex
        run: latexmk -shell-escape -pdf -Werror atlas-syllabus.tex
      - name: Compile LaTeX document atlas-bok.tex
        run: latexmk -shell-escape -pdf -Werror atlas-bok.tex
      - name: Compile LaTeX document sample-exam-questions.tex
        run: latexmk -shell-escape -pdf -Werror sample-exam-questions.tex
      - name: Compile LaTeX document sample-exam-answers.tex
        run: latexmk -shell-escape -pdf -Werror sample-exam-answers.tex
      - name: Upload PDF documents
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            example.pdf
            atlas-bok.pdf
            atlas-syllabus.pdf
            sample-exam-questions.pdf
            sample-exam-answers.pdf
      - name: Create a prerelease
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: The latest version
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            example.pdf
            atlas-bok.pdf
            atlas-syllabus.pdf
            sample-exam-questions.pdf
            sample-exam-answers.pdf
